### ISSUE TITLE
tests showing difference

### ISSUE THREAD

**Issue by rLannes** [Carldeboer/AMUSED#1]
Hi I installed amused and run the test. I got different results as I should get. Do you have any tips? 
```
./runTests.bat 
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test1:  23154  differences (should be 0)
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test2:  12321  differences (should be 0)
Scanning background sequences
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test3:  24994  differences (should be 0)
Scanning background sequences
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test4:  12022  differences (should be 0)
/home/romain/Logiciel/AMUSED/AMUSED-KS:24: warning: key "1p" is duplicated and overwritten on line 24
Inputing All Data...
Making BG...
Calculating statistics...
Sorting results...
Calculating P-values...
Printing results...
Done!
test5:  5537  differences (should be 0)
```

**Comment by Carldeboer** [comment]
what OS are you using? 
Can you run the following command?
```
zdiff test1.res.gz test/test1.s6.results.gz | head
```

**Comment by rLannes** [comment]
zdiff test1.res.gz test/test1.s6.results.gz | head
2,631c2,631
< 2	TG	CA	208	2446	8.503679476696648	1.5755088603886542	1.5755088603886545	6.612615287842879	5.071231850339562	1.5413834375033169
< 2	CG	CG	143	2446	5.846279640228945	0.5820872417017641	0.5820872417017641	-6.550276130001106	-0.6785015531500096	5.871774576851097
< 2	CT	AG	175	2446	7.1545380212591985	1.5330094837010715	1.5330094837010717	5.694840172234514	5.355145906675122	0.339694265559392
< 4	TGGA	TCCA	35	2438	1.435602953240361	2.4872781503943457	2.5011848890337087	5.579098673593663	3.0158662352943915	2.5632324382992713
< 2	TA	TA	33	2446	1.3491414554374488	0.41330109147000543	0.4133010914700055	-5.242506457891504	-2.1609137193120755	3.0815927385794284
< 4	TG-A	T-CA	77	2438	3.158326497128794	1.80187578059251	2.3990594179665665	5.2419157332269695	5.103034655361052	0.13888107786591775
< 5	CTG-A	T-CAG	47	2434	1.9309778142974527	2.0746705728280235	2.265042087081704	5.115047987562311	2.9936903389631047	2.121357648599206
< 3	CTG	CAG	101	2442	4.135954135954136	1.6504323161179117	1.6961869872049513	5.088197241399333	4.189071025575668	0.8991262158236646
< 4	AG-T	A-CT	63	2438	2.5840853158326498	1.8650216870833316	2.082619254542353	5.027537601786661	3.3512052968082076	1.6763323049784535

I am on unbuntu system.

here the stdout of the test:
./runTests.bat 
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test1:  23154  differences (should be 0)
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test2:  12321  differences (should be 0)
Scanning background sequences
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test3:  24994  differences (should be 0)
Scanning background sequences
Scanning foreground sequences
Input All Data, All Trees Built.
Adding gaps...
Calculating statistics... 
Sorting results...
Printing results...
All Done!
test4:  12022  differences (should be 0)
/samurlab1/RawData/Romain/Logiciel/AMUSED/AMUSED/AMUSED-KS:24: warning: key "1p" is duplicated and overwritten on line 24
Inputing All Data...
Making BG...
Calculating statistics...
Sorting results...
Calculating P-values...
Printing results...
Done!

**Comment by Carldeboer** [comment]
Actually, can you head both files being compared? Seems there are more substantial differences than I expected. 
```
gzip -dc test1.res.gz | head
gzip -dc test/test1.s6.results.gz | head
```
The goal is to figure out if there's a difference due to numerical precision (e.g. an underlying library is different leading to inconsequential differences), or if there is actually a big difference in the results (e.g. a problem in the code or your install).

For BROCKMAN, only the k-mer counts are used anyway.

**Comment by Carldeboer** [comment]
please re-open if you are able to provide the requested information.
